#+TITLE: ReasonConf 2019 OCaml Workshop

This repo contains exercises and build instructions to help you get started
developing in OCaml.

* Installing build tools and libraries
  See [[https://github.com/ocamllabs/install-ocaml/blob/master/README.org][README.org in install-ocaml]] for instructions.
* Exercises
  The [[file:02-exercises][exercises]] directory contains a number of exercises to get you started with
  OCaml. Each one has some expect-tests embedded in it. The workflow is:

  #+BEGIN_SRC bash
  cd 02-exercises/$problem_dir

  dune runtest # builds and runs inline tests
  # Look at test output and compiler errors, edit problem.ml, rerun:
  dune runtest
  #+END_SRC
* Github
  Now you're done with the exercises, dive into monads and implement a part
  of GitHub's own =hub= CLI, using the github library from MirageOS.

  See the [[file:03-github][github README]] to get started!
* Frogger
  Now you will implement a simplified clone of the classic arcade game Frogger.

  See the [[file:04-frogger][frogger README]] to get started!

* Documentation and resources
** OCaml
   - [[https://dev.realworldocaml.org/toc.html][Real World OCaml]]
   - [[http://caml.inria.fr/pub/docs/manual-ocaml/][OCaml manual]]
   - [[https://docs.mirage.io][MirageOS API Documentation]]
** Jane Street libraries and tools
   - [[https://opensource.janestreet.com/][An overview of Jane Street's open source things]]
   - [[https://ocaml.janestreet.com/ocaml-core/v0.10/doc/][Documentation for Core]]
** dune
   - [[https://www.youtube.com/watch?v=BNZhmMAJarw][Video tutorial]]
   - [[https://dune.readthedocs.io/en/latest/][Manual]]

